// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzW1-35vyIRtjNbce8C62dVPFbuv07eq0',
    appId: '1:650923938507:web:d2ea0c376a9da52c48c14e',
    messagingSenderId: '650923938507',
    projectId: 'gs-mvp-473aa',
    authDomain: 'gs-mvp-473aa.firebaseapp.com',
    databaseURL: 'https://gs-mvp-473aa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gs-mvp-473aa.appspot.com',
    measurementId: 'G-E3Y7LJXNEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtOangN9GwWoiIwDLlQm_phRb4JuQansg',
    appId: '1:650923938507:android:7694931e587c376448c14e',
    messagingSenderId: '650923938507',
    projectId: 'gs-mvp-473aa',
    databaseURL: 'https://gs-mvp-473aa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gs-mvp-473aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClE8H9gLu5YrJ-QyhSrjqfgG9igkvpgwQ',
    appId: '1:650923938507:ios:64948b984f0ebb1348c14e',
    messagingSenderId: '650923938507',
    projectId: 'gs-mvp-473aa',
    databaseURL: 'https://gs-mvp-473aa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gs-mvp-473aa.appspot.com',
    iosClientId: '650923938507-f3blqpf2gj2o5sbm0kc0unin9uqe3kc6.apps.googleusercontent.com',
    iosBundleId: 'com.example.gsMvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClE8H9gLu5YrJ-QyhSrjqfgG9igkvpgwQ',
    appId: '1:650923938507:ios:6f690e1beda9214148c14e',
    messagingSenderId: '650923938507',
    projectId: 'gs-mvp-473aa',
    databaseURL: 'https://gs-mvp-473aa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gs-mvp-473aa.appspot.com',
    iosClientId: '650923938507-iifulcvi5561tvj9bqjqrmbb60hko71q.apps.googleusercontent.com',
    iosBundleId: 'com.example.gsMvp.RunnerTests',
  );
}
